[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://governance.envisionedflow.com"
  to = "/governance/"
  status = 200
  force = true

[[redirects]]
  from = "https://governance.envisionedflow.com/*"
  to = "/governance/:splat"
  status = 200
  force = true
